name: Update Crowdin Contributors

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Install ts-node
        run: yarn global add ts-node
         
      - name: Set up git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"

      - name: Generate timestamp
        id: date
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        run: |
          git checkout -b "automated-update-${{ env.TIMESTAMP }}"

      - name: Run script
        run: npx ts-node -O '{"module":"commonjs"}' ./src/scripts/crowdin/getCrowdinContributors.ts
        env:
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}

      - name: Commit and push
        run: |
          git add -A
          git commit -m "Update Crowdin contributors at ${{ env.TIMESTAMP }}"
          git push origin "automated-update-${{ env.TIMESTAMP }}"

      - name: Create Pull Request
        run: |
          gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
          gh pr create --base dev --head "automated-update-${{ env.TIMESTAMP }}" --title "Automated update ${{ env.TIMESTAMP }}" --body "This PR was automatically created to update Crowdin contributors. This workflows runs every Sunday at 00:00 (UTC).\n\nThank you to everyone contributing to translate ethereum.org ❤️"
