name: Update Crowdin Contributors

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Install ts-node
        run: yarn global add ts-node

      - name: Run script
        run: npx ts-node -O '{"module":"commonjs"}' ./src/scripts/crowdin/getCrowdinContributors.ts
        env:
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
    
      - name: Generate timestamp
        id: date
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

      - name: Set up git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b automated-update-${{ steps.date.outputs.timestamp }}

      - name: Commit and push
        run: |
          git add -A
          git commit -m "Update Crowdin contributors"
          git fetch origin
          git rebase origin/dev
          git push origin automated-update-${{ steps.date.outputs.timestamp }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          branch: automated-update-${{ steps.date.outputs.timestamp }}
          title: Automated update ${{ steps.date.outputs.timestamp }}
          body: This is an automated update.
