name: Update Crowdin Contributors

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Install ts-node
        run: yarn global add ts-node
         
      - name: Set up git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"

      - name: Generate timestamp
        id: date
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Run script and Create Pull Request
        uses: peter-evans/create-pull-request@v3
        env:
          TIMESTAMP: ${{ env.TIMESTAMP }}
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          branch: automated-update-${{ env.TIMESTAMP }}
          title: Automated update ${{ env.TIMESTAMP }}
          body: This is an automated update.
          commit-message: "Update Crowdin contributors"
          script: |
            git fetch origin dev
            git checkout -b automated-update-${{ env.TIMESTAMP }} origin/dev
            npx ts-node -O '{"module":"commonjs"}' ./src/scripts/crowdin/getCrowdinContributors.ts
            git add -A
